import pg from 'pg';
const { Client } = pg;
const client = new Client({ connectionString: process.env.DATABASE_URL });
await client.connect();
await client.query("UPDATE ponto_companies SET module_triagem = true, module_arco_iris = true WHERE slug = 'principal'");
const t = await client.query("UPDATE triagens SET company_id = 1 WHERE company_id IS NULL");
const p = await client.query("UPDATE professionals SET company_id = 1 WHERE company_id IS NULL");
const pa = await client.query("UPDATE patients SET company_id = 1 WHERE company_id IS NULL");
const a = await client.query("UPDATE appointments SET company_id = 1 WHERE company_id IS NULL");
const w = await client.query("UPDATE waiting_list SET company_id = 1 WHERE company_id IS NULL");
const r = await client.query("SELECT id, name, slug, module_ponto, module_triagem, module_arco_iris FROM ponto_companies WHERE slug='principal'");
console.log('Company principal:', r.rows[0]);
console.log('triagens:', t.rowCount, '| professionals:', p.rowCount, '| patients:', pa.rowCount, '| appointments:', a.rowCount, '| waiting_list:', w.rowCount);
await client.end();
