export * from "./generated/api";
export type {
  AbsenceRecord,
  Appointment,
  AppointmentWithDetails,
  CreateAppointmentBody,
  CreatePatientBody,
  CreatePontoEmployeeBody,
  CreatePontoRecordBody,
  CreateProfessionalBody,
  CreateWaitingListEntryBody,
  DailySchedule,
  GetAppointmentsParams,
  GetPatientsParams,
  GetPontoRecordsParams,
  GetPontoSummaryParams,
  GetProfessionalScheduleParams,
  GetTodayAppointmentsParams,
  GetWaitingListParams,
  HealthStatus,
  Patient,
  PatientAbsenceInfo,
  PatientPdfData,
  PontoDaySummary,
  PontoEmployee,
  PontoRecord,
  Professional,
  ProfessionalCapacity,
  ScheduleSlot,
  UpdateAppointmentStatusBody,
  UpdatePatientBody,
  UpdateWaitingListEntryBody,
  VacancyAlert,
  WaitingListEntry,
} from "./generated/types";
