import { pgTable, serial, text, timestamp, boolean } from "drizzle-orm/pg-core";

export const triagens = pgTable("triagens", {
  id: serial("id").primaryKey(),
  nome: text("nome").notNull(),
  dataNascimento: text("data_nascimento"),
  idade: text("idade"),
  responsavel: text("responsavel"),
  telefone: text("telefone"),
  endereco: text("endereco"),
  naturalidade: text("naturalidade"),
  rg: text("rg"),
  cpf: text("cpf"),
  sus: text("sus"),
  nomeMae: text("nome_mae"),
  escolaridadeMae: text("escolaridade_mae"),
  profissaoMae: text("profissao_mae"),
  nomePai: text("nome_pai"),
  escolaridadePai: text("escolaridade_pai"),
  profissaoPai: text("profissao_pai"),
  numIrmaos: text("num_irmaos"),
  tipoImovel: text("tipo_imovel"),
  bolsaFamilia: boolean("bolsa_familia").default(false),
  bpc: boolean("bpc").default(false),
  diagnostico: text("diagnostico"),
  cid: text("cid"),
  medico: text("medico"),
  dataUltimaCons: text("data_ultima_cons"),
  profissional: text("profissional"),
  especialidade: text("especialidade"),
  data: text("data"),
  resultado: text("resultado"),
  respostas: text("respostas"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
